import React from 'react'

import localFont from "next/font/local";

const autography = localFont({
  src: "../fonts/Autography.woff",
  variable: "--font-autography",
  weight: "400",
});

function Testheader() {
  return (
    <section className="py-10 lg:py-24 px-5">
            <div className="max-w-5xl bg-white border rounded-3xl py-16 px-4 mx-auto sm:px-6 lg:px-8">
                <div className="mx-auto md:max-w-lg lg:max-w-3xl text-center">
                <h1  className={`relative text-4xl text-[#6B8C61] ${autography.className}`}>We Aim</h1>
                    <h2 className="text-3xl my-10 leading-tight text-[#33402E] sm:text-4xl lg:text-4xl lg:leading-tight">
                        <span className='font-bold'>To help ensure that the skincare industry becomes more sustainable, shifting towards a more circular economy.</span>
                    </h2>
                    <p className='text-gray-600 !leading-normal'>It is our mission to increase the use of recycling in the skincare industry and reduce the incorrect disposal of plastic waste produced through the industry. At Pure Purpose, we’re passionate about reducing the waste generated by the skincare industry. Our mission is to help businesses and consumers make sustainable choices by providing an eco-friendly solution for skincare packaging. We believe in a world where beauty doesn't come at the cost of the environment.</p>
                </div>

            </div>
        </section>
  )
}

export default Testheader